# Generated by Django 4.1.1 on 2022-10-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Почта')),
                ('username', models.CharField(max_length=25, verbose_name='Имя')),
                ('nickname', models.CharField(max_length=30, verbose_name='Никнейм')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('date', models.DateTimeField(verbose_name='Дата регистарции')),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('token_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('token', models.CharField(max_length=50, verbose_name='Токен')),
                ('date', models.DateTimeField(verbose_name='Дата генерации')),
                ('username_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='users.user')),
            ],
        ),
    ]
